/*

    CONCEPT: ENCAPSULATION                                             [ 5 MARKS ]
    
    Q1] Create a java Class Employee that demonstrates Encapsulation.
            The class should containbprivate Data Members such as:empId,name and salary.
            Provide Public getter and setter methods.
            Validate salary in setter so that salary must be greater than 0.
         
         Create a Main class, To set values and display employee Details.
         
         
    CONCEPT : INHERITANCE                                                [ 5 MARKS ]
    
    Q2] Create a java Program to demonstrate Inheritance using a Bank Account System,
            Create a Base class Account, containing accountNumber(Autogenerated), and Balance.
            
        Include Method Deposit(double amount),withdraw(double amount), and getBalance().
        
        Create Two Child Clases SavingAccount and CurrentAccount inheriting from Account(PARENT CLASS).

        Program:
        SavingAccount:
        Having a final Minimum Balance 500.
        Overrides Withdraw Method.
        Does not allow withdrawl if minimum balance condition is validated.

        CurrentAccount:
        Has an OverdraftLimit Variable.
        Override Withdraw Method.
        Allows withdrawls only if overdraft limit is not exceeded.

        Create a Program class having name and Account Object[Has a relationship].


        IN MAIN CLASS,
        Q] Create a Account for Smith with balance 2000.
        Create an account for katty with Balance 3000.
        Deposit 2000 into smith's account.
        Withdraw 2000 from kathy's account.

        DISPLAY  Updated Balance and show inheritance behaviour.


        
        
        
        */